name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t registration_sys_student_ui_image /RegistrationSys_StudentUI

      - name: Fail if build fails
        run: docker inspect registration_sys_student_ui_image || exit 1
